-- Generated by Database Engineer AI — OMEGA NEXUS OS
-- Project: Autonomous Drone Controller | App Type: GENERIC
-- Target: PostgreSQL 16 / SQLite 3

CREATE TABLE IF NOT EXISTS a59271c2_items (
    id         VARCHAR(64) PRIMARY KEY,
    title      VARCHAR(500) NOT NULL,
    category    VARCHAR(255) DEFAULT 'General',
    score    VARCHAR(255) DEFAULT '',
    status     VARCHAR(50) DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_a59271c2_items_status ON a59271c2_items(status);
CREATE INDEX IF NOT EXISTS idx_a59271c2_items_title  ON a59271c2_items(title);

-- Seed Data
INSERT INTO a59271c2_items (id, title, status) VALUES
    ('1', 'Autonomous Drone Controller Core Engine', 'ACTIVE'),
    ('2', 'AI Telemetry Pipeline', 'ACTIVE'),
    ('3', 'Security Cluster', 'VERIFIED')
ON CONFLICT (id) DO NOTHING;
