// Generated by 36 Trained AI Agents — OMEGA NEXUS OS
// Project: Quantum Circuit Simulator | App Type: TRADING | Tier: Frontend React 18

import React, { useState, useEffect, useCallback } from 'react';

const API = '/api/v1/quantum-circuit-simulator';

export default function QuantumCircuitSimulatorApp() {
  const [items, setItems] = useState([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [showModal, setShowModal] = useState(false);
  const [form, setForm] = useState({ title: '', status: 'ACTIVE' });

  const fetchItems = useCallback(async () => {
    try {
      const res = await fetch(`${API}/positions`);
      const data = await res.json();
      setItems(data.positions || data.items || []);
    } catch {
      setItems([{"id": "1", "title": "BTC Long Swing", "status": "OPEN"}, {"id": "2", "title": "ETH Short Hedge", "status": "OPEN"}, {"id": "3", "title": "NVDA Momentum", "status": "CLOSED"}]);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { fetchItems(); }, [fetchItems]);

  const addItem = async () => {
    if (!form.title.trim()) return;
    const item = { ...form, id: String(Date.now()), created: new Date().toISOString() };
    try {
      await fetch(`${API}/positions`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(item)
      });
    } catch {}
    setItems(prev => [item, ...prev]);
    setShowModal(false);
    setForm({ title: '', status: 'ACTIVE' });
  };

  const del = (id) => setItems(prev => prev.filter(i => String(i.id) !== String(id)));

  const filtered = items.filter(i =>
    (i.title || '').toLowerCase().includes(search.toLowerCase())
  );
  const activeCount = items.filter(i =>
    ['ACTIVE', 'Published', 'OPEN', 'Completed', 'Stable', 'Won'].includes(i.status)
  ).length;

  if (loading) return (
    <div style={{ display: 'flex', height: '100vh', alignItems: 'center', justifyContent: 'center', color: '#00F5FF', fontFamily: 'monospace' }}>
      Loading Quantum Circuit Simulator...
    </div>
  );

  return (
    <div style={{ maxWidth: 1200, margin: '0 auto', padding: 24, fontFamily: '"Space Grotesk", system-ui, sans-serif' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24, flexWrap: 'wrap', gap: 12 }}>
        <div>
          <h1 style={{ fontSize: 28, fontWeight: 900, color: '#fff', margin: 0 }}>🚀 Quantum Circuit Simulator</h1>
          <p style={{ color: '#64748b', fontSize: 12, marginTop: 4, fontFamily: 'monospace' }}>
            TRADING Platform | 36 AI Agents | Full CRUD | 3-Tier Full-Stack
          </p>
        </div>
        <div style={{ display: 'flex', gap: 10, alignItems: 'center' }}>
          <div style={{ padding: '8px 14px', background: 'rgba(0,245,255,0.08)', border: '1px solid rgba(0,245,255,0.2)', borderRadius: 10, textAlign: 'center' }}>
            <div style={{ fontSize: 8, color: '#64748b', fontFamily: 'monospace' }}>TOTAL</div>
            <div style={{ fontSize: 18, fontWeight: 900, color: '#00F5FF' }}>{items.length}</div>
          </div>
          <div style={{ padding: '8px 14px', background: 'rgba(0,255,136,0.08)', border: '1px solid rgba(0,255,136,0.2)', borderRadius: 10, textAlign: 'center' }}>
            <div style={{ fontSize: 8, color: '#64748b', fontFamily: 'monospace' }}>ACTIVE</div>
            <div style={{ fontSize: 18, fontWeight: 900, color: '#00FF88' }}>{activeCount}</div>
          </div>
          <button onClick={() => setShowModal(true)} style={{ padding: '10px 18px', borderRadius: 10, background: 'linear-gradient(90deg,#6E56FF,#00F5FF)', border: 'none', color: '#fff', fontWeight: 800, cursor: 'pointer' }}>
            + Add Position
          </button>
        </div>
      </div>

      <input
        value={search}
        onChange={e => setSearch(e.target.value)}
        placeholder="Search positions..."
        style={{ width: '100%', padding: '10px 14px', background: 'rgba(15,23,42,0.8)', border: '1px solid rgba(255,255,255,0.1)', borderRadius: 10, color: '#fff', fontSize: 13, boxSizing: 'border-box', marginBottom: 16 }}
      />

      <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
        {filtered.map(item => (
          <div key={item.id} style={{ padding: '14px 18px', background: 'rgba(8,12,38,0.9)', border: '1px solid rgba(0,245,255,0.12)', borderRadius: 12, display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 14 }}>
            <div style={{ flex: 1 }}>
              <div style={{ fontWeight: 700, color: '#f8fafc', fontSize: 14 }}>{item.title}</div>
              <div style={{ fontSize: 10, color: '#64748b', fontFamily: 'monospace', marginTop: 4 }}>
                ID: {String(item.id)} | Status: {item.status}
              </div>
            </div>
            <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
              <span style={{ fontSize: 9.5, color: '#00FF88', border: '1px solid rgba(0,255,136,0.3)', padding: '2px 10px', borderRadius: 20, fontFamily: 'monospace' }}>
                {item.status}
              </span>
              <button onClick={() => del(item.id)} style={{ background: 'rgba(239,68,68,0.15)', border: '1px solid rgba(239,68,68,0.3)', color: '#ef4444', borderRadius: 6, padding: '4px 10px', fontSize: 11, cursor: 'pointer' }}>
                Delete
              </button>
            </div>
          </div>
        ))}
        {filtered.length === 0 && (
          <div style={{ textAlign: 'center', padding: 32, color: '#64748b', fontFamily: 'monospace' }}>
            No positions found. Add the first one!
          </div>
        )}
      </div>

      {showModal && (
        <div onClick={() => setShowModal(false)} style={{ position: 'fixed', inset: 0, background: 'rgba(2,6,23,0.85)', backdropFilter: 'blur(12px)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 9999 }}>
          <div onClick={e => e.stopPropagation()} style={{ background: '#060d22', border: '1px solid #00F5FF', borderRadius: 18, padding: 28, width: 440, display: 'flex', flexDirection: 'column', gap: 14 }}>
            <h3 style={{ color: '#00F5FF', margin: 0, fontSize: 17 }}>+ New Position</h3>
            <input
              value={form.title}
              onChange={e => setForm(p => ({ ...p, title: e.target.value }))}
              placeholder="Enter title..."
              style={{ padding: '10px 14px', background: 'rgba(15,23,42,0.9)', border: '1px solid rgba(255,255,255,0.15)', borderRadius: 10, color: '#fff', fontSize: 13 }}
            />
            <input
              value={form.status || ''}
              onChange={e => setForm(p => ({ ...p, status: e.target.value }))}
              placeholder="Status (e.g. ACTIVE)..."
              style={{ padding: '10px 14px', background: 'rgba(15,23,42,0.9)', border: '1px solid rgba(255,255,255,0.15)', borderRadius: 10, color: '#fff', fontSize: 13 }}
            />
            <div style={{ display: 'flex', gap: 10, justifyContent: 'flex-end', marginTop: 4 }}>
              <button onClick={() => setShowModal(false)} style={{ padding: '9px 18px', borderRadius: 9, background: 'transparent', border: '1px solid rgba(255,255,255,0.2)', color: '#94a3b8', fontSize: 13, cursor: 'pointer' }}>
                Cancel
              </button>
              <button onClick={addItem} style={{ padding: '9px 20px', borderRadius: 9, background: 'linear-gradient(90deg,#6E56FF,#00F5FF)', border: 'none', color: '#fff', fontWeight: 800, fontSize: 13, cursor: 'pointer' }}>
                Save Position
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
