-- Generated by Database Engineer AI — OMEGA NEXUS OS
-- Project: Quantum Circuit Simulator | App Type: TRADING
-- Target: PostgreSQL 16 / SQLite 3

CREATE TABLE IF NOT EXISTS quantum_circuit_simulator_positions (
    id         VARCHAR(64) PRIMARY KEY,
    title      VARCHAR(500) NOT NULL,
    asset    VARCHAR(255) DEFAULT 'General',
    side    VARCHAR(255) DEFAULT '',
    status     VARCHAR(50) DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_quantum_circuit_simulator_positions_status ON quantum_circuit_simulator_positions(status);
CREATE INDEX IF NOT EXISTS idx_quantum_circuit_simulator_positions_title  ON quantum_circuit_simulator_positions(title);

-- Seed Data
INSERT INTO quantum_circuit_simulator_positions (id, title, status) VALUES
    ('1', 'BTC Long Swing', 'OPEN'),
    ('2', 'ETH Short Hedge', 'OPEN'),
    ('3', 'NVDA Momentum', 'CLOSED')
ON CONFLICT (id) DO NOTHING;
