# Generated by Database Engineer AI + Software Engineer AI — OMEGA NEXUS OS
# Project: MedTrack | ORM Data Models (Pydantic v2)

from pydantic import BaseModel, Field, ConfigDict
from typing import Optional, List, Dict, Any
from datetime import datetime
import uuid

class PatientBase(BaseModel):
    title: str = Field(..., min_length=1, max_length=500)
    condition: str = Field(default='General')
    blood_type: str = Field(default='')
    status: str = Field(default='ACTIVE')

class PatientCreate(PatientBase):
    id: Optional[str] = Field(default_factory=lambda: str(uuid.uuid4()))
    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict)

class PatientUpdate(BaseModel):
    title: Optional[str] = None
    condition: Optional[str] = None
    blood_type: Optional[str] = None
    status: Optional[str] = None

class PatientResponse(PatientBase):
    model_config = ConfigDict(from_attributes=True)
    id: str
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

class PatientList(BaseModel):
    patients: List[PatientResponse]
    total: int
    skip: int = 0
    limit: int = 100
