-- Generated by Database Engineer AI — OMEGA NEXUS OS
-- Project: MedTrack | App Type: HEALTHCARE
-- Target: PostgreSQL 16 / SQLite 3

CREATE TABLE IF NOT EXISTS medtrack_patients (
    id         VARCHAR(64) PRIMARY KEY,
    title      VARCHAR(500) NOT NULL,
    condition    VARCHAR(255) DEFAULT 'General',
    blood_type    VARCHAR(255) DEFAULT '',
    status     VARCHAR(50) DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_medtrack_patients_status ON medtrack_patients(status);
CREATE INDEX IF NOT EXISTS idx_medtrack_patients_title  ON medtrack_patients(title);

-- Seed Data
INSERT INTO medtrack_patients (id, title, status) VALUES
    ('P001', 'John Carter', 'Critical'),
    ('P002', 'Sarah Connor', 'Stable')
ON CONFLICT (id) DO NOTHING;
