# Generated by Database Engineer AI
# ORM Data Models for Test FullStack App

from pydantic import BaseModel, Field
from datetime import datetime
from typing import Optional

class RecordEntity(BaseModel):
    id: str = Field(..., description="Unique record identifier")
    title: str = Field(..., description="Name of record entry")
    status: str = Field(default="ACTIVE")
    score: float = Field(default=99.0, ge=0.0, le=100.0)
    created_at: Optional[datetime] = Field(default_factory=datetime.utcnow)

    class Config:
        json_schema_extra = {
            "example": {
                "id": "rec_01",
                "title": "Test FullStack App Production Module",
                "status": "ACTIVE",
                "score": 99.8
            }
        }
