-- Generated by Database Engineer AI & Software Engineer AI
-- Database Schema for Project: Test FullStack App
-- Target: PostgreSQL / CockroachDB

CREATE TABLE IF NOT EXISTS test_fullstack_app_records (
    id VARCHAR(64) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    status VARCHAR(50) DEFAULT 'ACTIVE',
    score NUMERIC(5, 2) DEFAULT 99.00,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_test_fullstack_app_status ON test_fullstack_app_records(status);

-- Seed Data Insertion
INSERT INTO test_fullstack_app_records (id, title, status, score)
VALUES 
    ('1', 'Test FullStack App Core Engine Module', 'ACTIVE', 99.4),
    ('2', 'Autonomous Agent Telemetry Pipeline', 'SYNCED', 98.9),
    ('3', 'Zero-Trust Security & DB Cluster', 'VERIFIED', 100.0)
ON CONFLICT (id) DO NOTHING;
