# Generated by Database Engineer AI + Software Engineer AI — OMEGA NEXUS OS
# Project: TaskBoard Pro | ORM Data Models (Pydantic v2)

from pydantic import BaseModel, Field, ConfigDict
from typing import Optional, List, Dict, Any
from datetime import datetime
import uuid

class TaskBase(BaseModel):
    title: str = Field(..., min_length=1, max_length=500)
    priority: str = Field(default='General')
    due_date: str = Field(default='')
    status: str = Field(default='ACTIVE')

class TaskCreate(TaskBase):
    id: Optional[str] = Field(default_factory=lambda: str(uuid.uuid4()))
    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict)

class TaskUpdate(BaseModel):
    title: Optional[str] = None
    priority: Optional[str] = None
    due_date: Optional[str] = None
    status: Optional[str] = None

class TaskResponse(TaskBase):
    model_config = ConfigDict(from_attributes=True)
    id: str
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

class TaskList(BaseModel):
    tasks: List[TaskResponse]
    total: int
    skip: int = 0
    limit: int = 100
