-- Generated by Database Engineer AI — OMEGA NEXUS OS
-- Project: TaskBoard Pro | App Type: TODO
-- Target: PostgreSQL 16 / SQLite 3

CREATE TABLE IF NOT EXISTS taskboard_pro_tasks (
    id         VARCHAR(64) PRIMARY KEY,
    title      VARCHAR(500) NOT NULL,
    priority    VARCHAR(255) DEFAULT 'General',
    due_date    VARCHAR(255) DEFAULT '',
    status     VARCHAR(50) DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_taskboard_pro_tasks_status ON taskboard_pro_tasks(status);
CREATE INDEX IF NOT EXISTS idx_taskboard_pro_tasks_title  ON taskboard_pro_tasks(title);

-- Seed Data
INSERT INTO taskboard_pro_tasks (id, title, status) VALUES
    ('1', 'TaskBoard Pro Sprint 1', 'In Progress'),
    ('2', 'Build Neural Engine', 'Completed'),
    ('3', 'WebSocket Telemetry Feed', 'Pending')
ON CONFLICT (id) DO NOTHING;
