-- Generated by Database Engineer AI — OMEGA NEXUS OS
-- Project: Cybersecurity Threat Scanner | App Type: GENERIC
-- Target: PostgreSQL 16 / SQLite 3

CREATE TABLE IF NOT EXISTS cybersecurity_threat_scanner_items (
    id         VARCHAR(64) PRIMARY KEY,
    title      VARCHAR(500) NOT NULL,
    category    VARCHAR(255) DEFAULT 'General',
    score    VARCHAR(255) DEFAULT '',
    status     VARCHAR(50) DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_cybersecurity_threat_scanner_items_status ON cybersecurity_threat_scanner_items(status);
CREATE INDEX IF NOT EXISTS idx_cybersecurity_threat_scanner_items_title  ON cybersecurity_threat_scanner_items(title);

-- Seed Data
INSERT INTO cybersecurity_threat_scanner_items (id, title, status) VALUES
    ('1', 'Cybersecurity Threat Scanner Core Engine', 'ACTIVE'),
    ('2', 'AI Telemetry Pipeline', 'ACTIVE'),
    ('3', 'Security Cluster', 'VERIFIED')
ON CONFLICT (id) DO NOTHING;
