# Generated by Database Engineer AI + Software Engineer AI — OMEGA NEXUS OS
# Project: TradingTerminal | ORM Data Models (Pydantic v2)

from pydantic import BaseModel, Field, ConfigDict
from typing import Optional, List, Dict, Any
from datetime import datetime
import uuid

class PositionBase(BaseModel):
    title: str = Field(..., min_length=1, max_length=500)
    asset: str = Field(default='General')
    side: str = Field(default='')
    status: str = Field(default='ACTIVE')

class PositionCreate(PositionBase):
    id: Optional[str] = Field(default_factory=lambda: str(uuid.uuid4()))
    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict)

class PositionUpdate(BaseModel):
    title: Optional[str] = None
    asset: Optional[str] = None
    side: Optional[str] = None
    status: Optional[str] = None

class PositionResponse(PositionBase):
    model_config = ConfigDict(from_attributes=True)
    id: str
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

class PositionList(BaseModel):
    positions: List[PositionResponse]
    total: int
    skip: int = 0
    limit: int = 100
