# Generated by Database Engineer AI + Software Engineer AI — OMEGA NEXUS OS
# Project: Bioinformatics Gene Profiler | ORM Data Models (Pydantic v2)

from pydantic import BaseModel, Field, ConfigDict
from typing import Optional, List, Dict, Any
from datetime import datetime
import uuid

class RecordBase(BaseModel):
    title: str = Field(..., min_length=1, max_length=500)
    category: str = Field(default='General')
    score: str = Field(default='')
    status: str = Field(default='ACTIVE')

class RecordCreate(RecordBase):
    id: Optional[str] = Field(default_factory=lambda: str(uuid.uuid4()))
    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict)

class RecordUpdate(BaseModel):
    title: Optional[str] = None
    category: Optional[str] = None
    score: Optional[str] = None
    status: Optional[str] = None

class RecordResponse(RecordBase):
    model_config = ConfigDict(from_attributes=True)
    id: str
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

class RecordList(BaseModel):
    items: List[RecordResponse]
    total: int
    skip: int = 0
    limit: int = 100
