-- Generated by Database Engineer AI — OMEGA NEXUS OS
-- Project: Bioinformatics Gene Profiler | App Type: GENERIC
-- Target: PostgreSQL 16 / SQLite 3

CREATE TABLE IF NOT EXISTS bioinformatics_gene_profiler_items (
    id         VARCHAR(64) PRIMARY KEY,
    title      VARCHAR(500) NOT NULL,
    category    VARCHAR(255) DEFAULT 'General',
    score    VARCHAR(255) DEFAULT '',
    status     VARCHAR(50) DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_bioinformatics_gene_profiler_items_status ON bioinformatics_gene_profiler_items(status);
CREATE INDEX IF NOT EXISTS idx_bioinformatics_gene_profiler_items_title  ON bioinformatics_gene_profiler_items(title);

-- Seed Data
INSERT INTO bioinformatics_gene_profiler_items (id, title, status) VALUES
    ('1', 'Bioinformatics Gene Profiler Core Engine', 'ACTIVE'),
    ('2', 'AI Telemetry Pipeline', 'ACTIVE'),
    ('3', 'Security Cluster', 'VERIFIED')
ON CONFLICT (id) DO NOTHING;
