# Generated by Database Engineer AI + Software Engineer AI — OMEGA NEXUS OS
# Project: CRM Nexus AI | ORM Data Models (Pydantic v2)

from pydantic import BaseModel, Field, ConfigDict
from typing import Optional, List, Dict, Any
from datetime import datetime
import uuid

class DealBase(BaseModel):
    title: str = Field(..., min_length=1, max_length=500)
    stage: str = Field(default='General')
    value: str = Field(default='')
    status: str = Field(default='ACTIVE')

class DealCreate(DealBase):
    id: Optional[str] = Field(default_factory=lambda: str(uuid.uuid4()))
    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict)

class DealUpdate(BaseModel):
    title: Optional[str] = None
    stage: Optional[str] = None
    value: Optional[str] = None
    status: Optional[str] = None

class DealResponse(DealBase):
    model_config = ConfigDict(from_attributes=True)
    id: str
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

class DealList(BaseModel):
    deals: List[DealResponse]
    total: int
    skip: int = 0
    limit: int = 100
