# Generated by Database Engineer AI + Software Engineer AI — OMEGA NEXUS OS
# Project: Blog Studio | ORM Data Models (Pydantic v2)

from pydantic import BaseModel, Field, ConfigDict
from typing import Optional, List, Dict, Any
from datetime import datetime
import uuid

class ArticleBase(BaseModel):
    title: str = Field(..., min_length=1, max_length=500)
    category: str = Field(default='General')
    author: str = Field(default='')
    status: str = Field(default='ACTIVE')

class ArticleCreate(ArticleBase):
    id: Optional[str] = Field(default_factory=lambda: str(uuid.uuid4()))
    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict)

class ArticleUpdate(BaseModel):
    title: Optional[str] = None
    category: Optional[str] = None
    author: Optional[str] = None
    status: Optional[str] = None

class ArticleResponse(ArticleBase):
    model_config = ConfigDict(from_attributes=True)
    id: str
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

class ArticleList(BaseModel):
    articles: List[ArticleResponse]
    total: int
    skip: int = 0
    limit: int = 100
