-- Generated by Database Engineer AI — OMEGA NEXUS OS
-- Project: Blog Studio | App Type: BLOG
-- Target: PostgreSQL 16 / SQLite 3

CREATE TABLE IF NOT EXISTS blog_studio_articles (
    id         VARCHAR(64) PRIMARY KEY,
    title      VARCHAR(500) NOT NULL,
    category    VARCHAR(255) DEFAULT 'General',
    author    VARCHAR(255) DEFAULT '',
    status     VARCHAR(50) DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_blog_studio_articles_status ON blog_studio_articles(status);
CREATE INDEX IF NOT EXISTS idx_blog_studio_articles_title  ON blog_studio_articles(title);

-- Seed Data
INSERT INTO blog_studio_articles (id, title, status) VALUES
    ('1', 'Synthesizing 36 AI Agents into OS', 'Published'),
    ('2', 'Full-Stack Code Gen from Prompts', 'Draft')
ON CONFLICT (id) DO NOTHING;
