-- Generated by Database Engineer AI — OMEGA NEXUS OS
-- Project: CRM Nexus | App Type: CRM
-- Target: PostgreSQL 16 / SQLite 3

CREATE TABLE IF NOT EXISTS crm_nexus_deals (
    id         VARCHAR(64) PRIMARY KEY,
    title      VARCHAR(500) NOT NULL,
    stage    VARCHAR(255) DEFAULT 'General',
    value    VARCHAR(255) DEFAULT '',
    status     VARCHAR(50) DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_crm_nexus_deals_status ON crm_nexus_deals(status);
CREATE INDEX IF NOT EXISTS idx_crm_nexus_deals_title  ON crm_nexus_deals(title);

-- Seed Data
INSERT INTO crm_nexus_deals (id, title, status) VALUES
    ('1', 'Nexus Robotics Corp', 'ACTIVE'),
    ('2', 'Cyberdyne Systems', 'ACTIVE'),
    ('3', 'Aperture Science', 'ACTIVE')
ON CONFLICT (id) DO NOTHING;
